package token

func IsCssValue(literal string) (subkind Subkind, ok bool) {
	if subkind, ok = IsCssKeywordValue(literal); ok {
		return
	}
	if subkind, ok = IsCssNamedColorValue(literal); ok {
		return
	}
	return SUBKIND_NONE, false
}

var CssKeywordValues = map[string]Subkind{
	"auto":      STANDARD_PROPERTY,
	"initial":   STANDARD_PROPERTY,
	"inherit":   STANDARD_PROPERTY,
	"unset":     STANDARD_PROPERTY,
	"light":     STANDARD_PROPERTY,
	"dark":      STANDARD_PROPERTY,
	"none":      STANDARD_PROPERTY,
	"solid":     STANDARD_PROPERTY,
	"underline": STANDARD_PROPERTY,
	"dotted":    STANDARD_PROPERTY,
	"dashed":    STANDARD_PROPERTY,
}

func IsCssKeywordValue(literal string) (subkind Subkind, ok bool) {
	subkind, ok = CssKeywordValues[literal]
	return
}

var CssNamedColorValues = map[string]Subkind{
	// Standard colors
	"black":   NAMED_COLOR_VALUE,
	"silver":  NAMED_COLOR_VALUE,
	"gray":    NAMED_COLOR_VALUE,
	"white":   NAMED_COLOR_VALUE,
	"maroon":  NAMED_COLOR_VALUE,
	"red":     NAMED_COLOR_VALUE,
	"purple":  NAMED_COLOR_VALUE,
	"fuchsia": NAMED_COLOR_VALUE,
	"green":   NAMED_COLOR_VALUE,
	"lime":    NAMED_COLOR_VALUE,
	"olive":   NAMED_COLOR_VALUE,
	"yellow":  NAMED_COLOR_VALUE,
	"navy":    NAMED_COLOR_VALUE,
	"blue":    NAMED_COLOR_VALUE,
	"teal":    NAMED_COLOR_VALUE,
	"aqua":    NAMED_COLOR_VALUE,
	// Extended colors
	"aliceblue":            NAMED_COLOR_VALUE,
	"antiquewhite":         NAMED_COLOR_VALUE,
	"aquamarine":           NAMED_COLOR_VALUE,
	"azure":                NAMED_COLOR_VALUE,
	"beige":                NAMED_COLOR_VALUE,
	"bisque":               NAMED_COLOR_VALUE,
	"blanchedalmond":       NAMED_COLOR_VALUE,
	"blueviolet":           NAMED_COLOR_VALUE,
	"brown":                NAMED_COLOR_VALUE,
	"burlywood":            NAMED_COLOR_VALUE,
	"cadetblue":            NAMED_COLOR_VALUE,
	"chartreuse":           NAMED_COLOR_VALUE,
	"chocolate":            NAMED_COLOR_VALUE,
	"coral":                NAMED_COLOR_VALUE,
	"cornflowerblue":       NAMED_COLOR_VALUE,
	"cornsilk":             NAMED_COLOR_VALUE,
	"crimson":              NAMED_COLOR_VALUE,
	"cyan":                 NAMED_COLOR_VALUE,
	"darkblue":             NAMED_COLOR_VALUE,
	"darkcyan":             NAMED_COLOR_VALUE,
	"darkgoldenrod":        NAMED_COLOR_VALUE,
	"darkgray":             NAMED_COLOR_VALUE,
	"darkgreen":            NAMED_COLOR_VALUE,
	"darkgrey":             NAMED_COLOR_VALUE,
	"darkkhaki":            NAMED_COLOR_VALUE,
	"darkmagenta":          NAMED_COLOR_VALUE,
	"darkolivegreen":       NAMED_COLOR_VALUE,
	"darkorange":           NAMED_COLOR_VALUE,
	"darkorchid":           NAMED_COLOR_VALUE,
	"darkred":              NAMED_COLOR_VALUE,
	"darksalmon":           NAMED_COLOR_VALUE,
	"darkseagreen":         NAMED_COLOR_VALUE,
	"darkslateblue":        NAMED_COLOR_VALUE,
	"darkslategray":        NAMED_COLOR_VALUE,
	"darkslategrey":        NAMED_COLOR_VALUE,
	"darkturquoise":        NAMED_COLOR_VALUE,
	"darkviolet":           NAMED_COLOR_VALUE,
	"deeppink":             NAMED_COLOR_VALUE,
	"deepskyblue":          NAMED_COLOR_VALUE,
	"dimgray":              NAMED_COLOR_VALUE,
	"dimgrey":              NAMED_COLOR_VALUE,
	"dodgerblue":           NAMED_COLOR_VALUE,
	"firebrick":            NAMED_COLOR_VALUE,
	"floralwhite":          NAMED_COLOR_VALUE,
	"forestgreen":          NAMED_COLOR_VALUE,
	"gainsboro":            NAMED_COLOR_VALUE,
	"ghostwhite":           NAMED_COLOR_VALUE,
	"gold":                 NAMED_COLOR_VALUE,
	"goldenrod":            NAMED_COLOR_VALUE,
	"greenyellow":          NAMED_COLOR_VALUE,
	"grey":                 NAMED_COLOR_VALUE,
	"honeydew":             NAMED_COLOR_VALUE,
	"hotpink":              NAMED_COLOR_VALUE,
	"indianred":            NAMED_COLOR_VALUE,
	"indigo":               NAMED_COLOR_VALUE,
	"ivory":                NAMED_COLOR_VALUE,
	"khaki":                NAMED_COLOR_VALUE,
	"lavender":             NAMED_COLOR_VALUE,
	"lavenderblush":        NAMED_COLOR_VALUE,
	"lawngreen":            NAMED_COLOR_VALUE,
	"lemonchiffon":         NAMED_COLOR_VALUE,
	"lightblue":            NAMED_COLOR_VALUE,
	"lightcoral":           NAMED_COLOR_VALUE,
	"lightcyan":            NAMED_COLOR_VALUE,
	"lightgoldenrodyellow": NAMED_COLOR_VALUE,
	"lightgray":            NAMED_COLOR_VALUE,
	"lightgreen":           NAMED_COLOR_VALUE,
	"lightgrey":            NAMED_COLOR_VALUE,
	"lightpink":            NAMED_COLOR_VALUE,
	"lightsalmon":          NAMED_COLOR_VALUE,
	"lightseagreen":        NAMED_COLOR_VALUE,
	"lightskyblue":         NAMED_COLOR_VALUE,
	"lightslategray":       NAMED_COLOR_VALUE,
	"lightslategrey":       NAMED_COLOR_VALUE,
	"lightsteelblue":       NAMED_COLOR_VALUE,
	"lightyellow":          NAMED_COLOR_VALUE,
	"limegreen":            NAMED_COLOR_VALUE,
	"linen":                NAMED_COLOR_VALUE,
	"magenta":              NAMED_COLOR_VALUE,
	"mediumaquamarine":     NAMED_COLOR_VALUE,
	"mediumblue":           NAMED_COLOR_VALUE,
	"mediumorchid":         NAMED_COLOR_VALUE,
	"mediumpurple":         NAMED_COLOR_VALUE,
	"mediumseagreen":       NAMED_COLOR_VALUE,
	"mediumslateblue":      NAMED_COLOR_VALUE,
	"mediumspringgreen":    NAMED_COLOR_VALUE,
	"mediumturquoise":      NAMED_COLOR_VALUE,
	"mediumvioletred":      NAMED_COLOR_VALUE,
	"midnightblue":         NAMED_COLOR_VALUE,
	"mintcream":            NAMED_COLOR_VALUE,
	"mistyrose":            NAMED_COLOR_VALUE,
	"moccasin":             NAMED_COLOR_VALUE,
	"navajowhite":          NAMED_COLOR_VALUE,
	"oldlace":              NAMED_COLOR_VALUE,
	"olivedrab":            NAMED_COLOR_VALUE,
	"orange":               NAMED_COLOR_VALUE,
	"orangered":            NAMED_COLOR_VALUE,
	"orchid":               NAMED_COLOR_VALUE,
	"palegoldenrod":        NAMED_COLOR_VALUE,
	"palegreen":            NAMED_COLOR_VALUE,
	"paleturquoise":        NAMED_COLOR_VALUE,
	"palevioletred":        NAMED_COLOR_VALUE,
	"papayawhip":           NAMED_COLOR_VALUE,
	"peachpuff":            NAMED_COLOR_VALUE,
	"peru":                 NAMED_COLOR_VALUE,
	"pink":                 NAMED_COLOR_VALUE,
	"plum":                 NAMED_COLOR_VALUE,
	"powderblue":           NAMED_COLOR_VALUE,
	"rebeccapurple":        NAMED_COLOR_VALUE,
	"rosybrown":            NAMED_COLOR_VALUE,
	"royalblue":            NAMED_COLOR_VALUE,
	"saddlebrown":          NAMED_COLOR_VALUE,
	"salmon":               NAMED_COLOR_VALUE,
	"sandybrown":           NAMED_COLOR_VALUE,
	"seagreen":             NAMED_COLOR_VALUE,
	"seashell":             NAMED_COLOR_VALUE,
	"sienna":               NAMED_COLOR_VALUE,
	"skyblue":              NAMED_COLOR_VALUE,
	"slateblue":            NAMED_COLOR_VALUE,
	"slategray":            NAMED_COLOR_VALUE,
	"slategrey":            NAMED_COLOR_VALUE,
	"snow":                 NAMED_COLOR_VALUE,
	"springgreen":          NAMED_COLOR_VALUE,
	"steelblue":            NAMED_COLOR_VALUE,
	"tan":                  NAMED_COLOR_VALUE,
	"thistle":              NAMED_COLOR_VALUE,
	"tomato":               NAMED_COLOR_VALUE,
	"transparent":          NAMED_COLOR_VALUE,
	"turquoise":            NAMED_COLOR_VALUE,
	"violet":               NAMED_COLOR_VALUE,
	"wheat":                NAMED_COLOR_VALUE,
	"whitesmoke":           NAMED_COLOR_VALUE,
	"yellowgreen":          NAMED_COLOR_VALUE,
}

func IsCssNamedColorValue(literal string) (subkind Subkind, ok bool) {
	subkind, ok = CssNamedColorValues[literal]
	return
}
